"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ExecutionState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ExecutionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ExecutionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _ExecutionState.ValueType  # 0
    """Default unspecified state."""
    RUNNING: _ExecutionState.ValueType  # 1
    """The operation is currently running."""
    SUCCEEDED: _ExecutionState.ValueType  # 2
    """The operation completed successfully."""
    FAILED: _ExecutionState.ValueType  # 3
    """The operation failed with an error."""
    CANCELLED: _ExecutionState.ValueType  # 4
    """The operation was cancelled."""

class ExecutionState(_ExecutionState, metaclass=_ExecutionStateEnumTypeWrapper):
    """Enum defining the possible states of an execution operation."""

UNSPECIFIED: ExecutionState.ValueType  # 0
"""Default unspecified state."""
RUNNING: ExecutionState.ValueType  # 1
"""The operation is currently running."""
SUCCEEDED: ExecutionState.ValueType  # 2
"""The operation completed successfully."""
FAILED: ExecutionState.ValueType  # 3
"""The operation failed with an error."""
CANCELLED: ExecutionState.ValueType  # 4
"""The operation was cancelled."""
global___ExecutionState = ExecutionState

@typing_extensions.final
class CommXchgRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the message to send.
    "sessions/{session_id}/executions/{execution_id}/msgs/{msg_id}/frm/{rank}".
    """
    data: builtins.bytes
    """The message to send."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "name", b"name"]) -> None: ...

global___CommXchgRequest = CommXchgRequest

@typing_extensions.final
class Session(google.protobuf.message.Message):
    """Represents a computation session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class PartyAddrsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    PARTY_ADDRS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the session. Format: "sessions/{session_id}".
    When used in CreateSessionRequest, name is session_id.
    """
    @property
    def party_addrs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Map of all participant addresses involved in this session."""
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Additional metadata for the session."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the session was created."""
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the session was last updated."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        party_addrs: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "metadata", b"metadata", "name", b"name", "party_addrs", b"party_addrs", "update_time", b"update_time"]) -> None: ...

global___Session = Session

@typing_extensions.final
class Execution(google.protobuf.message.Message):
    """Represents an execution operation within a session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class AttrsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.struct_pb2.Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    PROGRAM_FIELD_NUMBER: builtins.int
    INPUT_NAMES_FIELD_NUMBER: builtins.int
    OUTPUT_NAMES_FIELD_NUMBER: builtins.int
    RT_CONFIG_FIELD_NUMBER: builtins.int
    ATTRS_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the execution. Format:
    "sessions/{session_id}/executions/{execution_id}".
    When used in CreateExecutionRequest, name is execution_id.
    """
    program: builtins.bytes
    """The program binary to execute."""
    @property
    def input_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of input symbol resource names. Format examples:
        - "symbols/{symbol_id}" (global)
        - "sessions/{session_id}/executions/{execution_id}/symbols/{symbol_id}"
        """
    @property
    def output_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of output symbol resource names. Format examples:
        - "sessions/{session_id}/executions/{execution_id}/symbols/{symbol_id}"
        """
    @property
    def rt_config(self) -> google.protobuf.any_pb2.Any:
        """Configuration for execution runtime"""
    @property
    def attrs(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.struct_pb2.Value]:
        """Attributes for the execution, such as environment variables or
        additional parameters.
        """
    state: global___ExecutionState.ValueType
    """Current state of the execution."""
    error: builtins.str
    """Error message if the execution failed or was cancelled."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the execution was created."""
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the execution started."""
    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when the execution completed."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        program: builtins.bytes = ...,
        input_names: collections.abc.Iterable[builtins.str] | None = ...,
        output_names: collections.abc.Iterable[builtins.str] | None = ...,
        rt_config: google.protobuf.any_pb2.Any | None = ...,
        attrs: collections.abc.Mapping[builtins.str, google.protobuf.struct_pb2.Value] | None = ...,
        state: global___ExecutionState.ValueType = ...,
        error: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "end_time", b"end_time", "rt_config", b"rt_config", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attrs", b"attrs", "create_time", b"create_time", "end_time", b"end_time", "error", b"error", "input_names", b"input_names", "name", b"name", "output_names", b"output_names", "program", b"program", "rt_config", b"rt_config", "start_time", b"start_time", "state", b"state"]) -> None: ...

global___Execution = Execution

@typing_extensions.final
class Symbol(google.protobuf.message.Message):
    """Represents a symbol in a symbol table."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the symbol, when used in CreateSymbolRequest, name is
    symbol_id
    """
    data: builtins.bytes
    """Symbol data."""
    type: builtins.str
    """Type information of the symbol."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data: builtins.bytes = ...,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "name", b"name", "type", b"type"]) -> None: ...

global___Symbol = Symbol

@typing_extensions.final
class CreateSymbolRequest(google.protobuf.message.Message):
    """Request message for creating a symbol."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource where this symbol will be created.
    Only "" is supported for now.
    """
    @property
    def symbol(self) -> global___Symbol:
        """The symbol to create."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        symbol: global___Symbol | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["symbol", b"symbol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent", b"parent", "symbol", b"symbol"]) -> None: ...

global___CreateSymbolRequest = CreateSymbolRequest

@typing_extensions.final
class GetSymbolRequest(google.protobuf.message.Message):
    """Request message for retrieving a symbol."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the symbol to retrieve."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___GetSymbolRequest = GetSymbolRequest

@typing_extensions.final
class ListSymbolsRequest(google.protobuf.message.Message):
    """Request message for listing symbols."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The parent resource whose symbols are to be listed.
    - For global symbols, use "" or "symbols".
    - For session-level symbols, use "sessions/{session_id}".
    - For execution-level symbols, use
    "sessions/{session_id}/executions/{execution_id}".
    """
    page_size: builtins.int
    """The maximum number of symbols to return."""
    page_token: builtins.str
    """The token to retrieve the next page of results."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListSymbolsRequest = ListSymbolsRequest

@typing_extensions.final
class ListSymbolsResponse(google.protobuf.message.Message):
    """Response message for listing symbols."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Symbol]:
        """The list of symbols."""
    next_page_token: builtins.str
    """The token to retrieve the next page of results."""
    def __init__(
        self,
        *,
        symbols: collections.abc.Iterable[global___Symbol] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token", b"next_page_token", "symbols", b"symbols"]) -> None: ...

global___ListSymbolsResponse = ListSymbolsResponse

@typing_extensions.final
class UpdateSymbolRequest(google.protobuf.message.Message):
    """Request message for updating a symbol."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def symbol(self) -> global___Symbol:
        """The symbol to update.
        The `name` field must be set to the full resource name of the symbol.
        """
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The list of fields to be updated."""
    def __init__(
        self,
        *,
        symbol: global___Symbol | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["symbol", b"symbol", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["symbol", b"symbol", "update_mask", b"update_mask"]) -> None: ...

global___UpdateSymbolRequest = UpdateSymbolRequest

@typing_extensions.final
class DeleteSymbolRequest(google.protobuf.message.Message):
    """Request message for deleting a symbol."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of the symbol to delete."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___DeleteSymbolRequest = DeleteSymbolRequest

@typing_extensions.final
class CreateSessionRequest(google.protobuf.message.Message):
    """Request message for creating a session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    parent: builtins.str
    @property
    def session(self) -> global___Session: ...
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        session: global___Session | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["session", b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent", b"parent", "session", b"session"]) -> None: ...

global___CreateSessionRequest = CreateSessionRequest

@typing_extensions.final
class GetSessionRequest(google.protobuf.message.Message):
    """Request message for retrieving a session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___GetSessionRequest = GetSessionRequest

@typing_extensions.final
class ListSessionsRequest(google.protobuf.message.Message):
    """Request message for listing sessions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListSessionsRequest = ListSessionsRequest

@typing_extensions.final
class ListSessionsResponse(google.protobuf.message.Message):
    """Response message for listing sessions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def sessions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Session]: ...
    next_page_token: builtins.str
    def __init__(
        self,
        *,
        sessions: collections.abc.Iterable[global___Session] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token", b"next_page_token", "sessions", b"sessions"]) -> None: ...

global___ListSessionsResponse = ListSessionsResponse

@typing_extensions.final
class DeleteSessionRequest(google.protobuf.message.Message):
    """Request message for deleting a session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___DeleteSessionRequest = DeleteSessionRequest

@typing_extensions.final
class CreateExecutionRequest(google.protobuf.message.Message):
    """Request message for creating an execution."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    EXECUTION_FIELD_NUMBER: builtins.int
    parent: builtins.str
    @property
    def execution(self) -> global___Execution: ...
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        execution: global___Execution | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["execution", b"execution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["execution", b"execution", "parent", b"parent"]) -> None: ...

global___CreateExecutionRequest = CreateExecutionRequest

@typing_extensions.final
class GetExecutionRequest(google.protobuf.message.Message):
    """Request message for retrieving an execution."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___GetExecutionRequest = GetExecutionRequest

@typing_extensions.final
class ListExecutionsRequest(google.protobuf.message.Message):
    """Request message for listing executions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListExecutionsRequest = ListExecutionsRequest

@typing_extensions.final
class ListExecutionsResponse(google.protobuf.message.Message):
    """Response message for listing executions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def executions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Execution]: ...
    next_page_token: builtins.str
    def __init__(
        self,
        *,
        executions: collections.abc.Iterable[global___Execution] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["executions", b"executions", "next_page_token", b"next_page_token"]) -> None: ...

global___ListExecutionsResponse = ListExecutionsResponse

@typing_extensions.final
class DeleteExecutionRequest(google.protobuf.message.Message):
    """Request message for deleting an execution."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___DeleteExecutionRequest = DeleteExecutionRequest
