"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class InitRequest(google.protobuf.message.Message):
    """Request message for TEE session initialization"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    TEE_PARTY_ADDR_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    """The resource name of the session. Format: "sessions/{session_id}"."""
    tee_party_addr: builtins.str
    """Network address of the TEE party for communication"""
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        tee_party_addr: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["session_name", b"session_name", "tee_party_addr", b"tee_party_addr"]) -> None: ...

global___InitRequest = InitRequest

@typing_extensions.final
class InitResponse(google.protobuf.message.Message):
    """Response message for TEE session initialization
    Empty response indicating successful initialization
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___InitResponse = InitResponse

@typing_extensions.final
class GetTEEReportRequest(google.protobuf.message.Message):
    """Request message for TEE attestation report generation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    PEM_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    RANK_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    """The resource name of the session. Format: "sessions/{session_id}"."""
    pem_public_key: builtins.str
    """PEM-encoded public key for TEE attestation"""
    rank: builtins.int
    """Rank of the party in the TEE context"""
    nonce: builtins.str
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        pem_public_key: builtins.str = ...,
        rank: builtins.int = ...,
        nonce: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["nonce", b"nonce", "pem_public_key", b"pem_public_key", "rank", b"rank", "session_name", b"session_name"]) -> None: ...

global___GetTEEReportRequest = GetTEEReportRequest

@typing_extensions.final
class GetTEEReportResponse(google.protobuf.message.Message):
    """Response message for TEE attestation report"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEM_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    TEE_MODE_FIELD_NUMBER: builtins.int
    REPORT_JSON_FIELD_NUMBER: builtins.int
    pem_public_key: builtins.str
    """Public key for TEE party (PEM format)"""
    tee_mode: builtins.str
    """TEE mode: "sim" or "tdx" """
    report_json: builtins.str
    """The JSON serialized string of
    secretflowapis.v2.sdc.ual_pb2.UnifiedAttestationReport
    """
    def __init__(
        self,
        *,
        pem_public_key: builtins.str = ...,
        tee_mode: builtins.str = ...,
        report_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pem_public_key", b"pem_public_key", "report_json", b"report_json", "tee_mode", b"tee_mode"]) -> None: ...

global___GetTEEReportResponse = GetTEEReportResponse
