#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# This file will be auto-generated by MLIR's tablegen
# For now, we provide basic dialect registration

try:
    from ..ir import *  # noqa: F403
    from ._mplang_enum_gen import *  # noqa: F403
    from ._mplang_ops_gen import *  # noqa: F403
except ImportError:
    pass

from ._mplang_ops_ext import *  # noqa: F403
