//===- MpirDialect.h - Mpir dialect ----------------------------*- C++ -*-===//
//
// Mpir SPMD dialect declaration.
//
//===----------------------------------------------------------------------===//

#ifndef MPLANG_DIALECT_MPIR_MPIRDIALECT_H
#define MPLANG_DIALECT_MPIR_MPIRDIALECT_H

#include "mlir/IR/Dialect.h"

// Include the generated dialect class.
// This file is generated by TableGen in the build directory
#include "MpirDialect.h.inc"

#endif // MPLANG_DIALECT_MPIR_MPIRDIALECT_H
