# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import executor_pb2 as executor__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ExecutorServiceStub(object):
    """Service definition for managing symbols.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSymbol = channel.unary_unary(
                '/secretflow.ExecutorService/CreateSymbol',
                request_serializer=executor__pb2.CreateSymbolRequest.SerializeToString,
                response_deserializer=executor__pb2.Symbol.FromString,
                )
        self.GetSymbol = channel.unary_unary(
                '/secretflow.ExecutorService/GetSymbol',
                request_serializer=executor__pb2.GetSymbolRequest.SerializeToString,
                response_deserializer=executor__pb2.Symbol.FromString,
                )
        self.ListSymbols = channel.unary_unary(
                '/secretflow.ExecutorService/ListSymbols',
                request_serializer=executor__pb2.ListSymbolsRequest.SerializeToString,
                response_deserializer=executor__pb2.ListSymbolsResponse.FromString,
                )
        self.UpdateSymbol = channel.unary_unary(
                '/secretflow.ExecutorService/UpdateSymbol',
                request_serializer=executor__pb2.UpdateSymbolRequest.SerializeToString,
                response_deserializer=executor__pb2.Symbol.FromString,
                )
        self.DeleteSymbol = channel.unary_unary(
                '/secretflow.ExecutorService/DeleteSymbol',
                request_serializer=executor__pb2.DeleteSymbolRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CreateSession = channel.unary_unary(
                '/secretflow.ExecutorService/CreateSession',
                request_serializer=executor__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=executor__pb2.Session.FromString,
                )
        self.GetSession = channel.unary_unary(
                '/secretflow.ExecutorService/GetSession',
                request_serializer=executor__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=executor__pb2.Session.FromString,
                )
        self.ListSessions = channel.unary_unary(
                '/secretflow.ExecutorService/ListSessions',
                request_serializer=executor__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=executor__pb2.ListSessionsResponse.FromString,
                )
        self.DeleteSession = channel.unary_unary(
                '/secretflow.ExecutorService/DeleteSession',
                request_serializer=executor__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CreateExecution = channel.unary_unary(
                '/secretflow.ExecutorService/CreateExecution',
                request_serializer=executor__pb2.CreateExecutionRequest.SerializeToString,
                response_deserializer=executor__pb2.Execution.FromString,
                )
        self.GetExecution = channel.unary_unary(
                '/secretflow.ExecutorService/GetExecution',
                request_serializer=executor__pb2.GetExecutionRequest.SerializeToString,
                response_deserializer=executor__pb2.Execution.FromString,
                )
        self.ListExecutions = channel.unary_unary(
                '/secretflow.ExecutorService/ListExecutions',
                request_serializer=executor__pb2.ListExecutionsRequest.SerializeToString,
                response_deserializer=executor__pb2.ListExecutionsResponse.FromString,
                )
        self.DeleteExecution = channel.unary_unary(
                '/secretflow.ExecutorService/DeleteExecution',
                request_serializer=executor__pb2.DeleteExecutionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CommXchg = channel.unary_unary(
                '/secretflow.ExecutorService/CommXchg',
                request_serializer=executor__pb2.CommXchgRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ExecutorServiceServicer(object):
    """Service definition for managing symbols.
    """

    def CreateSymbol(self, request, context):
        """Creates a new symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbol(self, request, context):
        """Retrieves a symbol by its resource name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSymbols(self, request, context):
        """Lists symbols under a specified parent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSymbol(self, request, context):
        """Updates an existing symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSymbol(self, request, context):
        """Deletes a symbol by its resource name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Methods for managing Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExecution(self, request, context):
        """Methods for managing Execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExecution(self, request, context):
        """No UpdateExecution

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommXchg(self, request, context):
        """Methods for inter-party communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSymbol,
                    request_deserializer=executor__pb2.CreateSymbolRequest.FromString,
                    response_serializer=executor__pb2.Symbol.SerializeToString,
            ),
            'GetSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbol,
                    request_deserializer=executor__pb2.GetSymbolRequest.FromString,
                    response_serializer=executor__pb2.Symbol.SerializeToString,
            ),
            'ListSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSymbols,
                    request_deserializer=executor__pb2.ListSymbolsRequest.FromString,
                    response_serializer=executor__pb2.ListSymbolsResponse.SerializeToString,
            ),
            'UpdateSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSymbol,
                    request_deserializer=executor__pb2.UpdateSymbolRequest.FromString,
                    response_serializer=executor__pb2.Symbol.SerializeToString,
            ),
            'DeleteSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSymbol,
                    request_deserializer=executor__pb2.DeleteSymbolRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=executor__pb2.CreateSessionRequest.FromString,
                    response_serializer=executor__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=executor__pb2.GetSessionRequest.FromString,
                    response_serializer=executor__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=executor__pb2.ListSessionsRequest.FromString,
                    response_serializer=executor__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=executor__pb2.DeleteSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExecution,
                    request_deserializer=executor__pb2.CreateExecutionRequest.FromString,
                    response_serializer=executor__pb2.Execution.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=executor__pb2.GetExecutionRequest.FromString,
                    response_serializer=executor__pb2.Execution.SerializeToString,
            ),
            'ListExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutions,
                    request_deserializer=executor__pb2.ListExecutionsRequest.FromString,
                    response_serializer=executor__pb2.ListExecutionsResponse.SerializeToString,
            ),
            'DeleteExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExecution,
                    request_deserializer=executor__pb2.DeleteExecutionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CommXchg': grpc.unary_unary_rpc_method_handler(
                    servicer.CommXchg,
                    request_deserializer=executor__pb2.CommXchgRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secretflow.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """Service definition for managing symbols.
    """

    @staticmethod
    def CreateSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/CreateSymbol',
            executor__pb2.CreateSymbolRequest.SerializeToString,
            executor__pb2.Symbol.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/GetSymbol',
            executor__pb2.GetSymbolRequest.SerializeToString,
            executor__pb2.Symbol.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/ListSymbols',
            executor__pb2.ListSymbolsRequest.SerializeToString,
            executor__pb2.ListSymbolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/UpdateSymbol',
            executor__pb2.UpdateSymbolRequest.SerializeToString,
            executor__pb2.Symbol.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/DeleteSymbol',
            executor__pb2.DeleteSymbolRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/CreateSession',
            executor__pb2.CreateSessionRequest.SerializeToString,
            executor__pb2.Session.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/GetSession',
            executor__pb2.GetSessionRequest.SerializeToString,
            executor__pb2.Session.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/ListSessions',
            executor__pb2.ListSessionsRequest.SerializeToString,
            executor__pb2.ListSessionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/DeleteSession',
            executor__pb2.DeleteSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/CreateExecution',
            executor__pb2.CreateExecutionRequest.SerializeToString,
            executor__pb2.Execution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/GetExecution',
            executor__pb2.GetExecutionRequest.SerializeToString,
            executor__pb2.Execution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/ListExecutions',
            executor__pb2.ListExecutionsRequest.SerializeToString,
            executor__pb2.ListExecutionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/DeleteExecution',
            executor__pb2.DeleteExecutionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommXchg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secretflow.ExecutorService/CommXchg',
            executor__pb2.CommXchgRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
