# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttee.proto\x12\nsecretflow\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"r\n\x13GetTEEReportRequest\x12\x19\n\x0csession_name\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x1b\n\x0epem_public_key\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12#\n\x16generation_params_json\x18\x03 \x01(\tB\x03\xe0\x41\x02\"d\n\x14GetTEEReportResponse\x12\x1b\n\x0epem_public_key\x18\x01 \x01(\tB\x03\xe0\x41\x01\x12\x15\n\x08tee_mode\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x18\n\x0breport_json\x18\x03 \x01(\tB\x03\xe0\x41\x02\x32\x9d\x01\n\x15TEEAttestationService\x12\x83\x01\n\x0cGetTEEReport\x12\x1f.secretflow.GetTEEReportRequest\x1a .secretflow.GetTEEReportResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/{session_name=sessions/*}/tee_reportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tee_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTEEREPORTREQUEST.fields_by_name['session_name']._options = None
  _GETTEEREPORTREQUEST.fields_by_name['session_name']._serialized_options = b'\340A\002'
  _GETTEEREPORTREQUEST.fields_by_name['pem_public_key']._options = None
  _GETTEEREPORTREQUEST.fields_by_name['pem_public_key']._serialized_options = b'\340A\002'
  _GETTEEREPORTREQUEST.fields_by_name['generation_params_json']._options = None
  _GETTEEREPORTREQUEST.fields_by_name['generation_params_json']._serialized_options = b'\340A\002'
  _GETTEEREPORTRESPONSE.fields_by_name['pem_public_key']._options = None
  _GETTEEREPORTRESPONSE.fields_by_name['pem_public_key']._serialized_options = b'\340A\001'
  _GETTEEREPORTRESPONSE.fields_by_name['tee_mode']._options = None
  _GETTEEREPORTRESPONSE.fields_by_name['tee_mode']._serialized_options = b'\340A\002'
  _GETTEEREPORTRESPONSE.fields_by_name['report_json']._options = None
  _GETTEEREPORTRESPONSE.fields_by_name['report_json']._serialized_options = b'\340A\002'
  _TEEATTESTATIONSERVICE.methods_by_name['GetTEEReport']._options = None
  _TEEATTESTATIONSERVICE.methods_by_name['GetTEEReport']._serialized_options = b'\202\323\344\223\002*\022(/v1/{session_name=sessions/*}/tee_report'
  _globals['_GETTEEREPORTREQUEST']._serialized_start=88
  _globals['_GETTEEREPORTREQUEST']._serialized_end=202
  _globals['_GETTEEREPORTRESPONSE']._serialized_start=204
  _globals['_GETTEEREPORTRESPONSE']._serialized_end=304
  _globals['_TEEATTESTATIONSERVICE']._serialized_start=307
  _globals['_TEEATTESTATIONSERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
