"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    """The resource name of the session. Format: "sessions/{session_id}"."""
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_name", b"session_name"]) -> None: ...

global___InitRequest = InitRequest

@typing.final
class InitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___InitResponse = InitResponse

@typing.final
class GetTEEReportRequest(google.protobuf.message.Message):
    """Request message for TEE attestation report generation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_NAME_FIELD_NUMBER: builtins.int
    PEM_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    GENERATION_PARAMS_JSON_FIELD_NUMBER: builtins.int
    session_name: builtins.str
    """The resource name of the session. Format: "sessions/{session_id}"."""
    pem_public_key: builtins.str
    """PEM-encoded public key for TEE attestation"""
    generation_params_json: builtins.str
    """The JSON serialized string of
    secretflowapis.v2.sdc.ual_pb2.UnifiedAttestationGenerationParams
    """
    def __init__(
        self,
        *,
        session_name: builtins.str = ...,
        pem_public_key: builtins.str = ...,
        generation_params_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["generation_params_json", b"generation_params_json", "pem_public_key", b"pem_public_key", "session_name", b"session_name"]) -> None: ...

global___GetTEEReportRequest = GetTEEReportRequest

@typing.final
class GetTEEReportResponse(google.protobuf.message.Message):
    """Response message for TEE attestation report"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEM_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    TEE_MODE_FIELD_NUMBER: builtins.int
    REPORT_JSON_FIELD_NUMBER: builtins.int
    pem_public_key: builtins.str
    """Public key for TEE party (PEM format)"""
    tee_mode: builtins.str
    """TEE mode: "sim" or "tdx" """
    report_json: builtins.str
    """The JSON serialized string of
    secretflowapis.v2.sdc.ual_pb2.UnifiedAttestationReport
    """
    def __init__(
        self,
        *,
        pem_public_key: builtins.str = ...,
        tee_mode: builtins.str = ...,
        report_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pem_public_key", b"pem_public_key", "report_json", b"report_json", "tee_mode", b"tee_mode"]) -> None: ...

global___GetTEEReportResponse = GetTEEReportResponse
